### PR TITLE
Get fix for #6 into master. 

### PR DESCRIPTION
**Pull request by joseph-schaeffer**

### CODE REVIEW

**Comment by joseph-schaeffer** [comment]
Whoops, meant issue #6.

**Comment by joseph-schaeffer** [comment]
CLA was signed for the merge into Dev, @ktbolt: did you remove the autodesk.com email address from your github profile?

**Comment by ktbolt** [comment]
Yes I removed it.

**Comment by joseph-schaeffer** [comment]
@ktbolt: Ah, ok. You can probably leave it in your profile, if you want to still be credited for all the commits here. In either case, I think it's ok that we merged this here as you approved the CLA when it went into the dev branch. Thoughts?

**Comment by ktbolt** [comment]
i added my email back to my profile, don't want you to get all of the credit!

i think it's ok to merge. thanks.

**Comment by joseph-schaeffer** [comment]
Thanks! It's merged now and seems to be working. :) I'll try to add a test to catch reversion on this issue later.

**Pull request merged**
